# Generated by Django 3.2 on 2022-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_group_name',
            field=models.CharField(max_length=50, verbose_name='广告组名称'),
        ),
    ]
