# Generated by Django 3.2 on 2022-05-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_ad_ad_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='customer_search_terms',
            field=models.CharField(max_length=255, verbose_name='客户搜索词'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='launch',
            field=models.CharField(max_length=255, verbose_name='投放'),
        ),
    ]
