# Generated by Django 3.2 on 2022-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220517_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_campaign',
            field=models.CharField(max_length=1000, verbose_name='广告活动'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_group',
            field=models.CharField(max_length=100, verbose_name='广告组'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_group_name',
            field=models.CharField(max_length=100, verbose_name='广告组名称'),
        ),
    ]
